### PR TITLE
bump version to 1.7.8

### PR DESCRIPTION
**Pull request by jrochkind**
@mjgiarlo, I don't have permissions to actually merge this, perhaps because it's failing travis?
Would you mind merging this, trying to release a 1.7.8 that has no differences from 1.7.7 but

If this gets merged, I'll try to actually do a release, find out if I have
privileges to do that then I guess.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jrochkind HMU if something doesn't work and I can make sure you get all the bits you need.

**Comment by jrochkind** [comment]
@mjgiarlo I do not have privs to do a rubygems release of curation_concerns. (I seem to recall there was supposed to be some script that gave it to me everywhere? I guess not). 

~~~
$ bundle exec rake release
curation_concerns 1.7.8 built to pkg/curation_concerns-1.7.8.gem.
Tagged v1.7.8.
Pushed git commits and tags.
rake aborted!
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem. Ask an owner to add you with: gem owner curation_concerns --add jonathan@dnil.net
~~~

**Comment by mjgiarlo** [comment]
@jrochkind Can you add a PR that adds your GitHub username and Rubygems.org email address to this hash? https://github.com/samvera/hydra/blob/master/script/grant_revoke_gem_authority.rb#L23-L58

**Comment by jrochkind** [comment]
I could swear I already did that once, but apparently not! Or maybe I'm getting confused and thought someone told me after filling out the legal form I was supposed to be automatically added anywhere. Anyway, ok, sure, tomorrow.

**Pull request merged**
